### ISSUE TITLE
App doesn't honour configuration in "Video Conference"

### ISSUE THREAD

**Issue by putt1ck** [RocketChat/Apps.Jitsi#4]
With the slash jitsi app installed, the /jitsi command launches a conference on the public Jitsi server rather than the one configured for the RocketChat instance. Expected (security model) behaviour would be to default to the configured Jitsi Meet instance.

**Comment by christefano** [comment]
I can confirm this on my Rocket.Chat instance, as well.

Rocket.Chat version 3.2.2 here.

**Comment by putt1ck** [comment]
We found the config options for the app; this fixes the issue in one sense but unless RocketChat constructs are such that there's no way for the app to read the Jitsi config I'm tempted to leave this as an open issue.

**Comment by graywolf336** [comment]
Is it just a setting inside of Rocket.Chat? If so, what's the id of that setting?

**Comment by putt1ck** [comment]
Not sure what is meant by the ID of the setting (but happy to learn and then find it); it's accessed via admin -> Video Conference, in the Jitsi section "Domain"

**Comment by graywolf336** [comment]
Okay, then it probably does have one. Each Rocket.Chat setting has a unique id that describes it.

For example, here is the code that is responsible for creating that specific Rocket.Chat setting:

https://github.com/RocketChat/Rocket.Chat/blob/fb0cc0d6c2728491f64e9f390fb4fd1bf1b00831/app/videobridge/server/settings.js#L72-L80

**Comment by christefano** [comment]
I’ve noticed that when installed the Jitsi app _does_ indeed try to format links properly for the “Call” button on a Rocket.Chat user’s profile:

<img width="318" alt="Screen Shot 2020-05-21 at 1 10 38 PM" src="https://user-images.githubusercontent.com/105058/82602010-42075380-9b65-11ea-96a7-b2f87546b1ec.png">

So there’s that :) It’s just the `/jitsi` command that spits out URLs with meet.jit.si instead of the Jitsi domain I’ve entered under `Administration -> Video Conference -> Jitsi -> Domain`.

**Comment by graywolf336** [comment]
Version 1.0.0 of the App has been released to the Marketplace! 🎉  let me know if something doesn't work 😊
